//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_External_Req = new HashSet<tbl_External_Req>();
        }
    
        public int Customer_Id { get; set; }
        public string Customer__Name { get; set; }
        public string SPOC { get; set; }
        public string Email_Id { get; set; }
        public string Contact_Number { get; set; }
        public string Location { get; set; }
        public string Address { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_External_Req> tbl_External_Req { get; set; }
    }
}
