//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Internal_Req
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Internal_Req()
        {
            this.tbl_Select_Candidate = new HashSet<tbl_Select_Candidate>();
            this.tbl_Status = new HashSet<tbl_Status>();
        }
    
        public string Internal_Rqq_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Employee_Type { get; set; }
        public string Skill { get; set; }
        public Nullable<int> Reporting_Manager { get; set; }
        public Nullable<int> Cost_Center_Id { get; set; }
        public Nullable<int> Budget { get; set; }
        public Nullable<System.DateTime> Request_Raised_Date { get; set; }
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<System.DateTime> Notice_period { get; set; }
        public Nullable<double> Years_Of_Experience { get; set; }
        public Nullable<int> Sub_Id { get; set; }
        public Nullable<int> Bu_Id { get; set; }
    
        public virtual tbl_Business_Unit tbl_Business_Unit { get; set; }
        public virtual tbl_Cost_Center tbl_Cost_Center { get; set; }
        public virtual tbl_Employee_Type tbl_Employee_Type { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        public virtual tbl_User tbl_User1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Select_Candidate> tbl_Select_Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Status> tbl_Status { get; set; }
        public virtual tbl_Sub_Business_Unit tbl_Sub_Business_Unit { get; set; }
    }
}
