//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class tbl_Customer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_Customer()
        {
            this.tbl_External_Req = new HashSet<tbl_External_Req>();
        }
		[Required(ErrorMessage ="CustomerId is Required")]
        public int Customer_Id { get; set; }
		[Required(ErrorMessage = "CustomerName is Required")]
		public string Customer__Name { get; set; }
		[Required(ErrorMessage = "SPOC is Required")]
		public string SPOC { get; set; }
		[Required(ErrorMessage = "EmailId is Required")]
		public string Email_Id { get; set; }
		[Required(ErrorMessage = "ContactNumber is Required")]
		public string Contact_Number { get; set; }
		[Required(ErrorMessage = "Location is Required")]
		public string Location { get; set; }
		[Required(ErrorMessage = "Address is Required")]
		public string Address { get; set; }
		[Required(ErrorMessage = "CreationDate is Required")]
		[DataType(DataType.Date)]
		public Nullable<System.DateTime> Creation_Date { get; set; }
		[Required(ErrorMessage = "Flag is Required")]
		public string Flag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_External_Req> tbl_External_Req { get; set; }
    }
}
