//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
	using System.ComponentModel.DataAnnotations;

	public partial class tbl_Customer
    {
        public int Customer_Id { get; set; }
		[Required(ErrorMessage = "Please Enter Customer_Name.")]
		public string Customer__Name { get; set; }
		[Required(ErrorMessage = "Please Enter SPOC.")]
		public string SPOC { get; set; }
		[Required(ErrorMessage = "Please Enter Email_ID.")]
		[EmailAddress(ErrorMessage = "Please enter a Email_Id  Address.")]
		public string Email_Id { get; set; }
		[Required(ErrorMessage = "Please Enter Contact_Number.")]
		[RegularExpression(@"^\(?([0-9]{3})\)?[-. ]?([0-9]{3})[-. ]?([0-9]{4})$", ErrorMessage = "Not a valid Contact Number.")]
		public string Contact_Number { get; set; }
		[Required(ErrorMessage = "Please Enter Location.")]
		public string Location { get; set; }
		[Required(ErrorMessage = "Please Enter Address.")]
		public string Address { get; set; }
		[Required(ErrorMessage = "Please Enter Creation.")]
		public Nullable<System.DateTime> Creation_Date { get; set; }
		[Required(ErrorMessage = "Please Enter Flag.")]
		public string Flag { get; set; }
    }
}
