//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Status
    {
        public int Status_Id { get; set; }
        public string External_Rqq_Id { get; set; }
        public string Internal_Rqq_Id { get; set; }
        public string Message { get; set; }
        public string Status { get; set; }
        public Nullable<System.DateTime> Status_Date { get; set; }
        public Nullable<int> Flag { get; set; }
        public Nullable<int> User_Id { get; set; }
    
        public virtual tbl_External_Req tbl_External_Req { get; set; }
        public virtual tbl_Internal_Req tbl_Internal_Req { get; set; }
    }
}
