//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class tbl_User
    {
        public int Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        [Required(ErrorMessage="Employee_Name Is Required")]
        public string Employee_Name { get; set; }
        public string Email_Id { get; set; }
        public string Contact_Number { get; set; }
        [Required(ErrorMessage = "Password Is Required")]
        [DataType(DataType.Password)]
        public string Password { get; set; }
        public Nullable<System.DateTime> Password_Date { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public Nullable<System.DateTime> Created_Date { get; set; }
        public string Flag { get; set; }
        public string Reporting_Manager { get; set; }
    
        public virtual tbl_Role tbl_Role { get; set; }
    }
}
