//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_External_Req
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public tbl_External_Req()
        {
            this.tbl_Select_Candidate = new HashSet<tbl_Select_Candidate>();
            this.tbl_Status = new HashSet<tbl_Status>();
        }
    
        public string External_Rqq_Id { get; set; }
        public Nullable<int> Customer_Id { get; set; }
        public Nullable<int> Employee_Id { get; set; }
        public Nullable<int> Employee_Type { get; set; }
        public string Account_Manager { get; set; }
        public string Job_Location { get; set; }
        public string Resource_Location { get; set; }
        public Nullable<int> Current_CTC { get; set; }
        public Nullable<int> Expected_CTC { get; set; }
        public Nullable<System.DateTime> Request_Raised_date { get; set; }
        public Nullable<System.DateTime> Date_Of_Joining { get; set; }
        public Nullable<int> approved_Budget { get; set; }
        public Nullable<int> Margin { get; set; }
        public Nullable<System.DateTime> Notice_Period { get; set; }
        public Nullable<int> flag { get; set; }
        public Nullable<int> Role_Id { get; set; }
        public string Skills { get; set; }
        public Nullable<double> Years_Of_Experience { get; set; }
    
        public virtual tbl_Customer tbl_Customer { get; set; }
        public virtual tbl_Employee_Type tbl_Employee_Type { get; set; }
        public virtual tbl_User tbl_User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Select_Candidate> tbl_Select_Candidate { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tbl_Status> tbl_Status { get; set; }
    }
}
