//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DotNetReq2Offer.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tbl_Select_Candidate
    {
        public int Reference_number { get; set; }
        public Nullable<System.DateTime> Creation_Date { get; set; }
        public string Employee_Name { get; set; }
        public Nullable<int> Employee_Type { get; set; }
        public string Email_Id { get; set; }
        public string Contact_Number { get; set; }
        public string Job_Location { get; set; }
        public string External_Rqq_Id { get; set; }
        public string Internal_Rqq_Id { get; set; }
        public string Designation { get; set; }
        public Nullable<System.DateTime> Offer_Validity_Date { get; set; }
        public Nullable<int> CTC { get; set; }
        public Nullable<System.DateTime> Joining_Date { get; set; }
        public Nullable<int> Flag { get; set; }
    
        public virtual tbl_Employee_Type tbl_Employee_Type { get; set; }
        public virtual tbl_External_Req tbl_External_Req { get; set; }
        public virtual tbl_Internal_Req tbl_Internal_Req { get; set; }
    }
}
